### ISSUE TITLE
Init container failing on old pods

### ISSUE THREAD

**Issue by voxeljorge** [smallstep/autocert#173]
### Subject of the issue
We've been using autocert for a few months now and mostly things seem to work well, with one exception. Periodically we find that a number of pods enter into `PodInitializing` state and never move to `Running`. The pods this happen to are usually many days old, and on inspecting the container logs it seems that the `autocert-bootstrapper` container is failing.

### Environment
* Kubernetes version: 1.24
* Cloud provider or hardware configuration: EKS
* OS (e.g., from /etc/os-release): EKS Managed nodes
* Kernel (e.g., `uname -a`): EKS Managed nodes
* Install tools: N/A
* Other: N/A

### Steps to reproduce
These are theorized as I've not come up with a good way to reproduce this intentionally yet. See "Additional context" below for more info

- Set up autocert
- Create a pod with the correct autocert annotation
- Wait for `autocert-bootstrapper` credentials to expire
- force init cleaners to be cleaned up (not sure how to do this in EKS yet)
- observe the failure?
- 
### Expected behaviour
Pods with the autocert annotation should not fail to start up

### Actual behaviour
Pods with the autocert annotation fail start up

### Additional context
The init container failure itself is not super surprising given that `autocert-bootstrapper` is only really intended to work shortly after pod creation. I suspect that this issue is related to the following https://github.com/kubernetes/kubernetes/issues/67261

My theory here is that something is causing the init containers to get cleaned up, which is triggering Kubernetes to re-execute them. At the time they are re-executed the `autocert-bootstrapper` only has expired credentials which causes it to exit with an error, causing the stuck `PodInitializing` state. I'm currently looking for a way to force pods to be cleaned up in EKS to try to reproduce the failure.

A simple workaround that would probably be a reasonable addition in any case would be to modify the `bootstrapper.sh` script to check to see if credentails already exist, and `exit 0` if they do. This would at least allow the init container to re-run non-destructively.

**Comment by voxeljorge** [comment]
So I believe I found a way to reproduce the issue. By logging into the node which the pod is running on and killing the pod infrastructure container (`/pause` in the process tree under `ps axf` for my pod) the pod will fail to start. This might be a slightly different failure than the other one I had observed, but I can see a warning like this:

`Warning  Failed          76s                    kubelet  Error: secret "xxx-service.xxx-service.svc.cluster.local-afd6f" not found`

I'm not super familiar with the way the token handoff in autocert works but when I deleted the pod and inspected the new secret that looks similar, it appears to be an autocert token. I see that token bound to an environment variable in the init script which makes me think this failure might not be recoverable.

Killing the pod infrastructure container is obviously not something that should happen regularly, but it is mentioned here: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#pod-restart-reasons alongside another more likely reason for init containers to re-run.

**Comment by voxeljorge** [comment]
Above is a PR that I believe would resolve this issue. I'm working on testing it locally.

**Comment by mshearer76** [comment]
We were actually seeing this in our clusters after a node reboot. I was able to reproduce it by simply doing `crictl stops <pod>` on a pod that is injected with the autocert-bootstrap init-container. I have confirmed that this PR addresses our issue as well.
