### ISSUE TITLE
How to adjust the duration for a cert?

### ISSUE THREAD

**Issue by maxliu007** [smallstep/autocert#19]
How long can a cert last for by default? Align with step?
1. site.crt
2. root.crt

How can we adjust the duration for both? 
How and when renewal of certs will be executed?
It is not that easy for an App to cater the cert renewal in fact.

**Comment by maraino** [comment]
> How can we adjust the duration for both?

To configure the validity of `site.crt` look for the `autocert.step.sm/duration` anotation in https://github.com/smallstep/autocert#annotate-pods-to-get-certificates

But take into account that the provisioner in the configMap used to store the ca.json needs to support that duration, by default the default and maximum durations are set to 24h. So to increase that duration you will need to configure the claims in the provisioner. Look for the claims configuration (at provisioner or authority level) in https://smallstep.com/docs/step-ca/configuration#claims

To configure the validity of `root.crt` you will have to create your own root (and probably intermediate) using `step certificate create` and replace both certificates in the configMap used by `step-ca` to store the certificates, and (at least) the intermediate key in the secret used to store the keys.

To create the root and intermediate (1 year duration):
```
step certificate create root-ca root-ca.crt root-ca.key \
    --profile root-ca --not-after 8760h

step certificate create intermediate-ca intermediate-ca.crt intermediate-ca.key \
    --profile intermediate-ca --ca root-ca.crt --ca-key root-ca.key --not-after 8760h
```

> How and when renewal of certs will be executed?

With a duration of 24h the renewal will happen every 8h approx, it has a jitter, ~1/3 of the duration of the certificate.

> It is not that easy for an App to cater the cert renewal in fact.

You can add a monitor in the app or use some kind of file notifier as it's done in the nginx example, see https://github.com/smallstep/autocert/blob/master/examples/hello-mtls/nginx/certwatch.sh

**Comment by maraino** [comment]
I'm closing the issue, if you need more help you can add a discussion in https://github.com/smallstep/certificates/discussions
