### ISSUE TITLE
0.18.0 has no support arm64

### ISSUE THREAD

**Issue by satdeveloping** [smallstep/autocert#195]
### Subject of the issue
As discussed for a previous version in #15, the latest docker images do not support arm architectures. @dopey created an 0.17.2-rc1 image that did support both arm and amd. Since then, the issue has gone cold.

### Environment
* Kernel (e.g., `uname -a`): arm64

### Steps to reproduce
Try to run autocert v0.18.0 on an arm64 node

### Expected behaviour
Everything works as expected

### Actual behaviour
```
  Normal   Pulling    12s (x4 over 104s)  kubelet            Pulling image "smallstep/autocert-controller:0.18.0"
  Warning  Failed     9s (x4 over 101s)   kubelet            Failed to pull image "smallstep/autocert-controller:0.18.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/smallstep/autocert-controller:0.18.0": no match for platform in manifest: not found
  Warning  Failed     9s (x4 over 101s)   kubelet            Error: ErrImagePull
```

**Comment by hslatman** [comment]
Hey @satdeveloping, will discuss this later this week. Here's the branch @dopey was working on: https://github.com/smallstep/autocert/tree/max/arm64-docker.

**Comment by hslatman** [comment]
https://github.com/smallstep/autocert/pull/198 was merged

**Comment by satdeveloping** [comment]
Thanks @hslatman. Is there a timeline for a release?
