### ISSUE TITLE
Default docker images registry gone?

### ISSUE THREAD

**Issue by lmbaschiera** [smallstep/autocert#276]
### Subject of the issue
cr.step.sm docker registry cannot be resolved anymore as of Aug 28th, all pods are failing on pulling both the `autocert-bootstrapper` and `autocert-renewer` images.

### Environment
* Kubernetes version: 1.28.9
* Cloud provider or hardware configuration: AKS
* OS (e.g., from /etc/os-release): Irrelevant
* Kernel (e.g., `uname -a`): Irrelevant
* Install tools:
* Other:

### Steps to reproduce
Run `docker pull cr.step.sm/smallstep/autocert-bootstrapper:0.16.0`

### Expected behaviour
Docker image is pulled successfully

### Actual behaviour
`Error response from daemon: Get "https://cr.step.sm/v2/": dialing cr.step.sm:443 with direct connection: resolving host cr.step.sm: lookup cr.step.sm: no such host`

**Comment by hslatman** [comment]
Hi @lmbaschiera, you can use cr.smallstep.com. We'll update this issue later.

**Comment by hslatman** [comment]
The `cr.smallstep.com` resolves again. But we strongly advise to use `cr.smallstep.com` instead to prevent similar issues in the future.

**Comment by lmbaschiera** [comment]
I see - Thank you @hslatman!
