### ISSUE TITLE
Issue certificate for Job

### ISSUE THREAD

**Issue by slavb18** [smallstep/autocert#279]
### What would you like to be added
I need to issue certificate for  Job (not for Pod)

### Why this is needed
I am trying to setup temporal
https://github.com/temporalio/helm-charts/blob/main/charts/temporal/templates/server-job.yaml

I can add annotations **autocert.step.sm/name** for pods, but how to use it in Job ?

**Comment by areed** [comment]
For a Job you would need to set the annotations on the PodTemplateSpec at the path `job.spec.template.metadata.annotations`, but it looks like the [temporal chart doesn't support a configuration value to set custom annotations there](https://github.com/temporalio/helm-charts/blob/main/charts/temporal/templates/server-job.yaml#L11).

**Comment by slavb18** [comment]
> For a Job you would need to set the annotations on the PodTemplateSpec at the path `job.spec.template.metadata.annotations`, but it looks like the [temporal chart doesn't support a configuration value to set custom annotations there](https://github.com/temporalio/helm-charts/blob/main/charts/temporal/templates/server-job.yaml#L11).

A have added `job.spec.template.metadata.annotations`, but it doen't helps.
autocert-bootstrapper stuck in PodInitializing state 

becouse job is configured using [initContainers](https://github.com/temporalio/helm-charts/blob/c862ed89d4c274e94d76841f9d96cdb75b75ddb7/charts/temporal/templates/server-job.yaml#L26)

And certificate required inside initContainers
