### ISSUE TITLE
Release 0.19.5 is missing binaries

### ISSUE THREAD

**Issue by nicholasdille** [smallstep/autocert#285]
### Subject of the issue

The workflow for release 0.19.5 failed after ther creation of the GitHub release when uploading the binaries

### Environment

This issue affects the build tooling

### Steps to reproduce

I don't know

### Expected behaviour

A GitHub release should not exist if the workflow fails

### Actual behaviour

The release workflow fails but the GitHub release exists

### Additional context

None

**Comment by dopey** [comment]
Hey @nicholasdille 👋, thanks for the heads-up. Had a tag and SHA conflict. Reran the release process for v0.19.6 and should be good now.
