### ISSUE TITLE
If `sans` annotation is empty then apply the commonName as the only SAN

### ISSUE THREAD

**Issue by dopey** [smallstep/autocert#30]

**Comment by etasi** [comment]
The offending code seems to be here https://github.com/smallstep/autocert/blob/220f932bddbfaf720b3cda722e414ca203939dcb/controller/main.go#L474 as Michael Malone has already pointed out in the community chat. When sansAnnotationKey is not explicitly set per "autocert.step.sm/sans" annotation, the common name (admissionControllerAnnotationKey) should be set as the only sans.
