### ISSUE TITLE
John92630

### ISSUE THREAD

**Issue by john92630** [smallstep/autocert#32]
### Subject of the issue
Describe your issue here

### Environment
* Kubernetes version:
* Cloud provider or hardware configuration:
* OS (e.g., from /etc/os-release):
* Kernel (e.g., `uname -a`):
* Install tools:
* Other:

### Steps to reproduce
Tell us how to reproduce this issue

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Additional context
Add any other context about the problem here

**Comment by maraino** [comment]
@john92630 did you find an issue?

**Comment by dopey** [comment]
Let us know if the issue keeps coming up. Closing for now.
