### ISSUE TITLE
Recommended way to handle autocert failures

### ISSUE THREAD

**Issue by hiattp** [smallstep/autocert#46]
Apologies if this is obvious (I'm new to k8s in general) but what do you recommend for managing cert acquisition failures? I don't know why we see this so frequently but in a non-trivial number of pod boot-ups we see some kind of failure in sourcing certs and get into a perpetual (or at least long-running) `CrashLoopBackoff` on the pod, the cert container doesn't recover:

<img width="979" alt="Screen Shot 2021-12-13 at 1 29 16 PM" src="https://user-images.githubusercontent.com/571459/145883878-47fffa48-b7a3-47a8-bf2f-b54580f4e885.png">

Looks like we're using a slightly older version of the helm chart, I'll update and see if that decreases the incidence rate. Meanwhile, here are some logs from the renewer:

```bash
~ % kubectl logs sidekiq-6f5f9557c-scgq4 -n sqjobs --container autocert-renewer
open /var/run/autocert.step.sm/site.crt: no such file or directory
error loading certificates
github.com/smallstep/cli/command/ca.renewCertificateAction
	/home/travis/gopath/src/github.com/smallstep/cli/command/ca/renew.go:239
github.com/smallstep/cli/command.ActionFunc.func1
	/home/travis/gopath/src/github.com/smallstep/cli/command/command.go:48
github.com/urfave/cli.HandleAction
	/home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:521
github.com/urfave/cli.Command.Run
	/home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.2/command.go:174
github.com/urfave/cli.(*App).RunAsSubcommand
	/home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:404
github.com/urfave/cli.Command.startApp
	/home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.2/command.go:373
github.com/urfave/cli.Command.Run
	/home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.2/command.go:102
github.com/urfave/cli.(*App).Run
	/home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:276
main.main
	/home/travis/gopath/src/github.com/smallstep/cli/cmd/step/main.go:93
runtime.main
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/runtime/proc.go:203
runtime.goexit
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/runtime/asm_amd64.s:1373
```

Thanks!

**Comment by maraino** [comment]
The container `autocert-bootstrapper` is the one that creates that file, you might be able to see the reason why the file is not there using `-c autocert-bootstrapper`.

I've also noticed that you're running an old version of the renewer (0.12.2), the latest version is (0.15.1). That might be related, but I'm not sure.

**Comment by maraino** [comment]
In that specific test where the file is not there, my recommendation is just to restart the pod after figuring out why the file is not there, was it created by autocert-bootstrapped? did somebody move it later?

In other error scenarios where the certificate has expired, you can also restart or manually create the certificate using:
```sh
$ kubectl exec -it <pod> -- bash
bash-5.1# cd /var/run/autocert.step.sm
bash-5.1# step ca certificate <domain> site.crt  site.key
```

You can also recover the root using
```sh
bash-5.1# step ca roots > root.crt
```

You might need to bootstrap `step` using if the environment proper variables are not set or the root is not present.
```sh
step ca bootstrap --ca-url https://<ca> --fingerprint <fingerprint>
```

**Comment by hiattp** [comment]
Thanks @maraino really appreciate the guidance. I'll look into the `autocert-bootstrapper` logs and upgrade to the latest version of autocert but while investigating our latest crash loop backoffs it seems like the more common scenario is that for some reason pods annotated with `autocert.step.sm/name: myapp.svc.cluster.local` don't receive the `autocert-bootstrapper` init container under some conditions (this seems to be uncommon, maybe 10% of the time). Perhaps when the `autocert` pod is booting/restarting at exactly the same time?

Not sure if you'd have any insight on how to mitigate that but meanwhile this seems like a pod scheduling issue on our end, not necessarily an issue with autocert itself so will close out this ticket. Thanks again!

**Comment by maraino** [comment]
@hiattp You can use multiple replicas of autocert to ensure a rollout restart if for example you're upgrading to a new version.
