### ISSUE TITLE
Add Support for Kubernetes v1.22+

### ISSUE THREAD

**Issue by com98** [smallstep/autocert#47]
### Subject of the issue
Hi!

I recently tried setting up autocert! I really like the idea and think the project itself is pretty cool! However, I encountered a problem when trying to setup Kubernetes in my Kubernetes v1.23.3 cluster and I'd appreciate if you could have a look.

The general problem is that Kubernetes removed the `admissionregistration.k8s.io/v1beta1` API - instead recommends to use `admissionregistration.k8s.io/v1`. (see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#removal-of-several-beta-kubernetes-apis). This causes your autocert webhook to not work anymore in Kubernetes versions from 1.22 (creation of the webhook fails).

I've managed to create the webhook using `admissionregistration.k8s.io/v1` in the definition, but even though the webhook is working the Kubernetes API pod does not accept its patch response (I suppose because it's still using `admissionregistration.k8s.io/v1beta1`).

### Environment
* Kubernetes version: v1.23.3
* Cloud provider or hardware configuration: Hosted vServer
* OS (e.g., from /etc/os-release): Debian 5.10.92-1 (2022-01-18) x86_64
* Kernel (e.g., `uname -a`): 5.10.0-11-amd64
* Install tools: -
* Other: -

### Steps to reproduce
Setup a Kubernetes v1.22+ cluster and try to get autocert working.

### Expected behaviour
The webhook should be created and responding properly so that the Pod creation requests is patched correctly.  

### Actual behaviour
The webhook can not be created and Kubernetes API refuses the JSON response from the Autocert Controller pod. 

Thanks a lot in advance!

If you have any questions, feel free to get back to me!

Best regards,
Lukas

**Comment by maraino** [comment]
Currently, autocert helm chart installs step-certificates by default, but this is deprecated and will be removed at some point. Here are instructions on how to configure autocert with your own CA and if the `ca` block is passed the `step-certificates` won't be installed.

**Comment by com98** [comment]
Thanks a lot! Using the Helm chart did the trick.
