### ISSUE TITLE
Fail to build from source: Confused paths in Dockerfile

### ISSUE THREAD

**Issue by Moosemorals** [smallstep/autocert#56]
### Subject of the issue
autocert/controller fails to build from source: 

### Environment
* Kubernetes version: v1.23.6+k3s1
* Cloud provider or hardware configuration: Mythic Beasts, 2 core/4GB
* OS (e.g., from /etc/os-release): Debian GNU/Linux 11 (bullseye)
* Kernel (e.g., `uname -a`): 5.10.0-14-amd64
* Install tools:
* Other:

### Steps to reproduce
```
$ git clone git@github.com:smallstep/autocert.git
remote: Enumerating objects: 403, done.
remote: Counting objects: 100% (98/98), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 403 (delta 55), reused 49 (delta 45), pack-reused 305
Receiving objects: 100% (403/403), 12.30 MiB | 10.68 MiB/s, done.
Resolving deltas: 100% (186/186), done.
$ cd autocert/controller
$ ls
client.go  Dockerfile  main.go  main_test.go
$  podman build -t registry.example.com/autocert-controller:latest .
STEP 1: FROM golang:alpine AS build-env
STEP 2: RUN apk update && apk upgrade &&     apk add --no-cache git
--> Using cache f39dccf9375503088d2edd71a3a33f4b8faee9f848d8674d5dfb6a848553f623
--> f39dccf9375
STEP 3: WORKDIR $GOPATH/src/github.com/autocert/controller
--> Using cache 098b974975a4aa137a0d25808f2a5eb11c4a87ce89910e40ab23ce1afb351c53
--> 098b974975a
STEP 4: COPY go.mod go.sum ./
STEP 5: FROM smallstep/step-cli:0.17.2
Error: error building at STEP "COPY go.mod go.sum ./": error adding sources [/tmp/autocert/controller/go.mod /tmp/autocert/controller/go.sum]: error checking on source /tmp/autocert/controller/go.mod under "/tmp/autocert/controller": copier: stat: "/go.mod": no such file or directory
$ 
```
### Expected behaviour
autocert/controller should build in a container

### Actual behaviour
build fails as `go.mod` and `go.sum` are in the parent directory.

### Additional context
Copying `go.mod` and `go.sum` to autocert/controller doesn't help, since the Dockerfile then expects to find `client.go` and `main.go` in a folder called `controller` (relative to the Dockerfile).

My guess is that the Dockerfile used to be in the root of the project and has been moved?

**Comment by Moosemorals** [comment]
Update: It's not the docker file, it's the docs :smile:

```
$ pwd
/tmp/autocert
$ podman build -t registry.example.com/autocert-controller:latest -f controller/Dockerfile .
[...]
[Build Success]
$ 
```

**Comment by tashian** [comment]
Thanks @Moosemorals, I've confirmed this issue and have fixed it in the README.
